# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            효징
tagline:          'A Jekyll theme'
description:      '매일 한개라도 의미있는 포스트를'
url:              https://kimhyojin.github.io
baseurl:          /

author:
  name:           'Kim Hyo Jin'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kimhyojin
