title: Kimcats
description: for technical blog + cats
author: KimHyoJin
logo: /static/img/profile.jpeg
github: https://github.com/kimhyojin
about:

baseurl: ""
url: ""

allowsearch: true

share:
  twitter_username: \kimcats0313
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
